[package]
name = "tim"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
  'event',
  'my_proc_macros',
]
exclude = [
  'tests/mock_repos/rust1'
]

[workspace.dependencies]
crossterm = "0.26.1"
regex = "1.8.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
crossterm.workspace = true
regex.workspace = true
log = "0.4.17"
ropey = "1.6.0"
simple-logging = "2.0.2"
tree-sitter = "0.20.9"
tree-sitter-javascript = "0.20.0"
tree-sitter-rust = "0.20.3"
tree-sitter-traversal = "0.1.2"
itertools = "0.10.5"
tree-sitter-typescript = "0.20.2"
tree-sitter-md = "0.1.5"
portable-pty = "0.8.1"
vt100 = "0.15.2"
diffy = "0.3.0"
ast-grep-core = "0.5.2"
dyn-clone = "1.0.11"
git2 = "0.17.1"
grep-searcher = "0.1.11"
grep-regex = "0.1.11"
lsp-types = "0.94.0"
serde_json = "1.0.96"
serde = "1.0.163"
json-rpc-types = "1.3.0"
uuid = {version="1.3.3", features = ["v4"]}
arboard = "3.2.0"
event = {path = "event"}
my_proc_macros = {path = "my_proc_macros"}
pretty_assertions = "1.3.0"
tree-sitter-highlight = "0.20.1"
rand = "0.8.5"
convert_case = "0.6.0"
ignore = "0.4.20"
crossbeam = "0.8.2"

[dev-dependencies]
tempfile = "3.6.0"
pretty_assertions = "1.3.0"
insta = { version = "1.29.0", features = [] }
fs_extra = "1.3.0"
rand = "0.8.5"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
