[package]
name = "editor-idea"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cc = "*"
crossterm = "0.26.1"
log = "0.4.17"
ropey = "1.6.0"
simple-logging = "2.0.2"
termion = "2.0.1"
tree-sitter = "0.20.9"
tree-sitter-javascript = "0.20.0"
tree-sitter-rust = "0.20.3"

[build-dependencies]
cc="*"
