name: github pages

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
          
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: '0.4.10'
      
      - name: Setup mdbook-linkcheck
        run: |
          mkdir -p mdbook-linkcheck && cd "$_" && \
          curl -L https://github.com/Michael-F-Bryan/mdbook-linkcheck/releases/latest/download/mdbook-linkcheck.x86_64-unknown-linux-gnu.zip -o mdbook-linkcheck.zip && \
          unzip "$_" && \
          chmod +x mdbook-linkcheck && \
          sudo mv mdbook-linkcheck /usr/bin
      
      - run: mdbook build ./docs/
      
      - run: ls ./docs/book/html/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./docs/book/html/ # The folder the action should deploy.